version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "movie-rec-movielens-tag-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kcec0inoid7z"
s3_prefix = "movie-rec-movielens-tag-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["InferenceFunction=943742432997.dkr.ecr.us-east-1.amazonaws.com/movierecmovielenstagappd98beeb3/inferencefunction7c73919drepo"]
disable_rollback = true
